name: 'Update Flake Locks'
description: 'Updates all flake lock files in the repository.'
runs:
  using: "composite"
  steps:
    - name: Update Flake Locks
      shell: bash
      run: |
        nix flake update --flake ./core
        nix flake update --flake ./extra/kernel/cachyos
        nix flake update
        if [ -f .github/scripts/get-hosts.sh ]; then
          hosts=$(bash .github/scripts/get-hosts.sh | jq -r '.[]')
          for host in $hosts; do
            echo "Updating flake lock for host: $host"
            nix flake update --flake ./vps/$host
          done
        fi
