name: 'Update Flake Locks'
description: 'Updates all flake lock files in the repository.'
runs:
  using: "composite"
  steps:
    - name: Update Flake Locks
      shell: bash
      run: |
        nix flake update --flake ./core
        nix flake update --flake ./extra/kernel/cachyos
        nix flake update --flake ./extra/kernel/cachyos-unstable
        nix flake update
        nix flake update --flake ./vps/tohu
        nix flake update --flake ./vps/hyperv
